const featuredJobs = [
  {
    id: 1,
    title: "Email Marketing",
    company: "Revolut",
    location: "Madrid, Spain",
    type: "Full Time",
    categories: ["Marketing", "Design"],
    description: "Revolut is looking for Email Marketing to help team marketing...",
  },
  {
    id: 2,
    title: "Brand Designer",
    company: "Dropbox",
    location: "San Fransisco, US",
    type: "Full Time",
    categories: ["Design", "Business"],
    description: "Dropbox is looking for Brand Designer to help the team t...",
  },
  {
    id: 3,
    title: "Email Marketing",
    company: "Pitch",
    location: "Berlin, Germany",
    type: "Full Time",
    categories: ["Marketing"],
    description: "Pitch is looking for Customer Manager to join marketing t...",
  },
  {
    id: 4,
    title: "Visual Designer",
    company: "Blinkist",
    location: "Granada, Spain",
    type: "Full Time",
    categories: ["Design"],
    description: "Blinkist is looking for Visual Designer to help team desi...",
  },
  {
    id: 5,
    title: "Product Designer",
    company: "ClassPass",
    location: "Manchester, UK",
    type: "Full Time",
    categories: ["Marketing", "Design"],
    description: "ClassPass is looking for Product Designer to help us...",
  },
  {
    id: 6,
    title: "Lead Designer",
    company: "Canva",
    location: "Ontario, Canada",
    type: "Full Time",
    categories: ["Design", "Business"],
    description: "Canva is looking for Lead Engineer to help develop n...",
  },
  {
    id: 7,
    title: "Brand Strategist",
    company: "GoDaddy",
    location: "Marseille, France",
    type: "Full Time",
    categories: ["Marketing"],
    description: "GoDaddy is looking for Brand Strategist to join the team...",
  },
  {
    id: 8,
    title: "Data Analyst",
    company: "Twitter",
    location: "San Diego, US",
    type: "Full Time",
    categories: ["Technology"],
    description: "Twitter is looking for Data Analyst to help team desi...",
  },
];

export default featuredJobs;
